package ExceptionDemo;

import java.util.Scanner;

public class ExceptionAss4 {

	//@SuppressWarnings("resource")
	public static void main(String[] args) throws Exception {
//		Scanner sc = new Scanner(System.in);
//        boolean flag = false;
//        String[] empNames = { "anand","harikrishna", "avinash", "eshwar", "sampath", "shashank", "ajaryya" };
//        System.out.println("Enter the names:");
//        String name = sc.next();
//        for (int i = 0; i < empNames.length; ++i) {
//            if (empNames[i].equalsIgnoreCase(name)) {
//                flag=true;
//                System.out.println("He is the existing employee");
//            }
//        }
//        if(flag==false)
//        {
//        	
//                throw new Exception("He is not Existing Employee");
//            
//            }
//        sc.close();
	}	 

	}
